from __future__ import annotations

from seojuice._async import AsyncSEOJuice
from seojuice._exceptions import (
    APIError,
    AuthError,
    ForbiddenError,
    NotFoundError,
    RateLimitError,
    SEOJuiceError,
    ServerError,
)
from seojuice._pagination import PagedResult, async_auto_paginate, auto_paginate
from seojuice._sync import SEOJuice
from seojuice._types import (
    AccessibilityIssue,
    ActionItem,
    ActionItemGroup,
    ActionItemSummary,
    AISOResponse,
    AnalysisQueued,
    AnalysisResult,
    BacklinkDomain,
    BacklinkItem,
    BenchmarkResponse,
    BulkActionResult,
    ChangeRecord,
    ChangeSettings,
    ChangeStats,
    ChangeWebhookPayload,
    ClusterDetail,
    ClusterSummary,
    Competitor,
    ContentDecayAlert,
    ContentGap,
    ContentQualityResponse,
    DomainHealthResponse,
    GBPLocation,
    GBPLocationsResponse,
    GBPReview,
    GBPReviewReplyResponse,
    GeoReadinessResponse,
    IntelligenceSummary,
    KeywordItem,
    LinkItem,
    MetricsSnapshot,
    PageContentResponse,
    PageDetail,
    PageKeyword,
    PageSpeedResponse,
    PageSummary,
    ReportCreated,
    ReportDetail,
    ReportSummary,
    SearchStat,
    SERPLandscapeResponse,
    SimilarPagesResponse,
    TopologyResponse,
    WebsiteDetail,
    WebsiteListResponse,
)

__version__ = "1.1.0"

__all__ = [
    "SEOJuice",
    "AsyncSEOJuice",
    "PagedResult",
    "auto_paginate",
    "async_auto_paginate",
    "SEOJuiceError",
    "APIError",
    "AuthError",
    "ForbiddenError",
    "NotFoundError",
    "RateLimitError",
    "ServerError",
    # Domain types
    "AccessibilityIssue",
    "ActionItem",
    "ActionItemGroup",
    "ActionItemSummary",
    "AISOResponse",
    "AnalysisQueued",
    "AnalysisResult",
    "BacklinkDomain",
    "BacklinkItem",
    "BenchmarkResponse",
    "BulkActionResult",
    "ChangeRecord",
    "ChangeSettings",
    "ChangeStats",
    "ChangeWebhookPayload",
    "ClusterDetail",
    "ClusterSummary",
    "Competitor",
    "ContentDecayAlert",
    "ContentGap",
    "ContentQualityResponse",
    "DomainHealthResponse",
    "GBPLocation",
    "GBPLocationsResponse",
    "GBPReview",
    "GBPReviewReplyResponse",
    "GeoReadinessResponse",
    "IntelligenceSummary",
    "KeywordItem",
    "LinkItem",
    "MetricsSnapshot",
    "PageContentResponse",
    "PageDetail",
    "PageKeyword",
    "PageSpeedResponse",
    "PageSummary",
    "ReportCreated",
    "ReportDetail",
    "ReportSummary",
    "SearchStat",
    "SERPLandscapeResponse",
    "SimilarPagesResponse",
    "TopologyResponse",
    "WebsiteDetail",
    "WebsiteListResponse",
]
